unbind r
bind r run-shell 'tmux source-file "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"' \; display-message "Config reloaded"

set -g prefix C-a
set -g mouse on
# don't rename windows automatically
set-option -g allow-rename off

# switch panes using Meta-<hjkl>
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# panes start at 1, not 0!
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
